"""
══════════════════════════════════════════
DATA PIPELINE — REPLACE WITH REAL SOURCE
══════════════════════════════════════════
This is a placeholder. To integrate real data:
1. Replace the source URL/connection string below
2. Update the schema mapping in the SCHEMA_MAP dict
3. Remove the synthetic generator call

Current behavior: reads from /data/customers.json (generated by generate_synthetic.py)
"""

import asyncio
import json
import logging
import sys
from pathlib import Path
from datetime import datetime

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

logger = logging.getLogger(__name__)

# ─────────────────────────────────────────────────────────────────────────────
# TODO: Replace this with real customer data source (CRM, CSV, API)
# Examples:
#   source = "https://crm.example.com/api/customers"   # REST API
#   source = "s3://bucket/customers.csv"               # S3 CSV
#   source = "postgresql://prod_db/customers"          # Production DB
# ─────────────────────────────────────────────────────────────────────────────

DEFAULT_SOURCE = "backend/data/customers.json"

SCHEMA_MAP = {
    # "source_field": "db_field"
    # TODO: Update these mappings when connecting real CRM
    "id": "id",
    "name": "name",
    "email": "email",
    "mobile": "mobile",
    "ltv": "ltv",
    "churn_risk": "churn_risk",
    "created_at": "created_at",
}


async def ingest_customer_data(source: str = DEFAULT_SOURCE) -> int:
    """
    Ingest customer records from source into the database.

    Args:
        source: Path or URL to customer data.
                TODO: Replace JSON file read with real CRM connector.

    Returns:
        Number of customers ingested.
    """
    # TODO: Replace this block with real data source connector
    # ── STUB: Read from local JSON ────────────────────────────────────────
    source_path = Path(source)
    if not source_path.exists():
        logger.warning("Source file not found: %s — run generate_synthetic.py first", source)
        return 0

    with open(source_path) as f:
        raw_data = json.load(f)

    logger.info("Loaded %d customer records from %s", len(raw_data), source)

    # Apply schema mapping
    mapped_customers = []
    for record in raw_data:
        mapped = {
            db_field: record.get(src_field)
            for src_field, db_field in SCHEMA_MAP.items()
        }
        mapped_customers.append(mapped)

    # Persist to database
    from app.database import AsyncSessionLocal, init_db
    from app.models.customer import Customer

    await init_db()

    async with AsyncSessionLocal() as session:
        for data in mapped_customers:
            # Upsert by email
            from sqlalchemy import select
            result = await session.execute(
                select(Customer).where(Customer.email == data["email"])
            )
            existing = result.scalar_one_or_none()

            if existing:
                existing.ltv = data["ltv"]
                existing.churn_risk = data["churn_risk"]
            else:
                customer = Customer(
                    name=data["name"],
                    email=data["email"],
                    mobile=data.get("mobile", "9000000000"),
                    ltv=float(data.get("ltv", 0)),
                    churn_risk=float(data.get("churn_risk", 0)),
                )
                session.add(customer)

        await session.commit()

    logger.info("✅ Ingested %d customers into database", len(mapped_customers))
    return len(mapped_customers)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    count = asyncio.run(ingest_customer_data())
    print(f"Ingested {count} customers")
